export { default as Home } from './Home/Home'
export { default as Menu } from './About/About'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Booking } from './Booking/Booking'
export { default as Register } from './Register/Register'
export { default as Login } from './Login/Login'
